<a href="https://colab.research.google.com/github/arunslb123/PyTorch-Tutorial/blob/master/pytorch_beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
a = torch.tensor([1,2,3,4,5,6])

In [8]:
a.dtype

torch.int64

In [9]:
b = torch.FloatTensor([1,2,3,4,5,6])
b.dtype

torch.float32

In [10]:
b.size()

torch.Size([6])

In [11]:
c = torch.Tensor([1,2,3])
c.dtype

torch.float32

In [12]:
b.view(3,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [13]:
a = torch.arange(9)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
a.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [0]:
a = torch.arange(27)
a = a.view(3,3,3)

In [16]:
a

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [17]:
a[1,1,1]

tensor(13)

In [0]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3]).view(3,1)

In [19]:
a

tensor([1, 2, 3])

In [20]:
b

tensor([[1],
        [2],
        [3]])

In [21]:
a*b

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [23]:
a@b

tensor([14])

In [24]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3])
torch.dot(a,b)

tensor(14)

In [26]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [0]:
y = 5*x**2 + 20*x 

In [28]:
y.backward()
x.grad

tensor(40.)